### ISSUE TITLE
add missing colon

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#102]
I am interested in services that accept these payments (add a colon): under all check boxes add an instruction *For more results, select all that apply. If you are interested in seeing ALL facilities regardless of payment, type click next.

**Comment by eeeschwartz** [comment]
Still need to add a mechanism for the help text below the checkboxes "*For more results, select all that apply. If you are interested in seeing ALL facilities regardless of payment, type click next"

The easiest option would be to include the help text below the question. I'll check with Amy.
