### ISSUE TITLE
[non-facet data] add website for facilities information

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#107]
add a “website” column in the spreadsheet if not already available. 

when facilities information is revealed to the user on expansion of the facility card, pull the website URL from the appropriate column. 

format the URL so that it can be click and targets "_blank" to open a new window/tab.

**Comment by ronnorthrip** [comment]
closed by Add web_url property assignment to getjson row reader #135 (feature/107_add_website_link_to_facilities_listing)
