### ISSUE TITLE
investigate why serves pregnant women does not appear in the facility listing

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#109]
Serves pregnant women facet does not appear in facility listing

**Comment by nikolaiwarner** [comment]
Like, it doesnt show that information in the listview when expanded?

**Comment by chaserx** [comment]
![screen shot 2016-08-25 at 3 53 57 pm](https://cloud.githubusercontent.com/assets/7292/17983767/42db0bfc-6adc-11e6-8e8f-4da65f2e762a.png)

This is from our user testing event. I'm disappointed that I didn't write more context around this. I can't remember if this is a data problem (certain known facilities not appearing in the results) or if there's something wrong with facet logic itself for this question

**Comment by nikolaiwarner** [comment]
I did notice that the question only appears if you chose facilities that serve women in the previous question.... that seems to be the expected behavior.

**Comment by seanmercier777** [comment]
Is this still an issue that needs resolving? It does seem like the question is only appropriate for 'female' persons.

**Comment by chaserx** [comment]
yeah. let's close this. I think this might be fixed.

**Comment by chaserx** [comment]
closing for now...
