### ISSUE TITLE
Merge static facility list into spreadsheet (for assessment, and medical detox)

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/gethelplex#114]
When we do:
- Our stakeholders can manage their content in realtime through the [Google spreadsheet](https://docs.google.com/spreadsheets/d/1ubx07oylGxk5FDIjMnQo4cMNBd3a8QYiPm27rWuyByI/pubhtml)
- Facilities will be displayed consistently in the [results list](https://cloud.githubusercontent.com/assets/428684/13527455/05d500e2-e1dd-11e5-996f-b92a1b143170.png), rather than sometimes in a [modal](https://cloud.githubusercontent.com/assets/428684/13527439/f24ab760-e1dc-11e5-9265-00a3aaa060ec.png)

Related: #112

**Comment by nikolaiwarner** [comment]
Should this be a separate new google spreadsheet, an additional sheet in the the current spreadsheet, or all merged into the one sheet?

**Comment by chaserx** [comment]
IDK. @eeeschwartz ?

**Comment by eeeschwartz** [comment]
I think they'd be in the same spreadsheet and they'd be distinguished by fields the same way that residential or outpatient facilities are.  So we'd probably add fields like:
- twelve_step_offered
- assessment_offered
- medical_detox_offered

Which would allow us to display these facilities based on the same decision tree mechanism that the site's built on.

## Caveat 1

This one gets into a can of worms and for that reason, I'd say we should tackle the higher priority #124 first.

## Caveat 2

Ultimately, this will effect the end user experience, so we'd probably want to run a quick prototype of it by Voices of Hope and SAVI. 

@nikolaiwarner how does this approach sound to your ears? If you +1, then maybe you could prototype it on a fork so we can demo the changes on another gh-pages instance?

**Comment by eeeschwartz** [comment]
Sorry partners, I fat fingered that last comment ^^. It's updated now!

**Comment by eeeschwartz** [comment]
Paraphrasing Shelley: 

* This will apply to medical detox and assessment
* 12 step resources can still be static but let's find a different place to put the link

When entering the site, the first question will read “Are you interested in services for:”

**Comment by ronnorthrip** [comment]
Feature/114 move assessments and detox into spreadhseet #137 closes this issue
