### ISSUE TITLE
add county filter

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#124]
county data should be available soon although the completion date for the data survey is unknown at this time. 

add a filter to narrow selections by county adjusting the map as necessary which will likely require getting the geographic centers of each county

**Comment by nikolaiwarner** [comment]
My first thought for this is to include a select box that contains the names of all counties and default at "All Counties" at the top of the Facilities list... then the user can select a county when then shows only facilities from that county and updates and centers the map. Am I on track?

**Comment by eeeschwartz** [comment]
@nikolaiwarner sounds legit to me

**Comment by nikolaiwarner** [comment]
Kewl. If I find it easy, I'd like to add similar selects for the other filterable facets
