### ISSUE TITLE
add the following to the 12-step popover

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#125]
Double Trouble in Recovery- A recovery group for people recovering from mental
illness and substance abuse.

Participation Station
869 Sparta Court                      
Lexington, KY
Thursdays 12-1:00 p.m.
Sunday 3-4:00 p.m.
For more information, please contact (859) 492-6997

The Community Inn                                    
824 Winchester Road
Lexington, KY
Thursdays 7:30-8:30 p.m.
For more information, please contact (859) 312-0707

Eastern State Hospital                                                      
627 West Fourth Street
Lexington, KY
Participation in the meeting is limited to current hospital patients only

**Comment by nikolaiwarner** [comment]
Is this data hard coded into the modal html or is it pulled from a spreadsheet?

**Comment by nikolaiwarner** [comment]
Actually, #114 suggests that it's not set in the spreadsheet.

**Comment by nikolaiwarner** [comment]
Nevermind. Found that everything's in index.html :kissing_closed_eyes:  ....Lots of mysterious red herrings in this repo.
