### ISSUE TITLE
Add ability to move back to previous question

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/gethelplex#13]
### How the questionnaire works

The questionnaire hacks the search facets to display one facet at a time. The facetOffset variable determines which facet to show.

The mechanism to move to the next question works like this:
- The 'next' button has the `data-next-facet-offset` attribute [set to the current offset + 1](https://github.com/openlexington/finda/blob/gh-pages/src/ui/facet.js#L99)
- The click handler [sets facetOffset to the +1 value](https://github.com/openlexington/finda/blob/gh-pages/src/ui/facet.js#L124) and renders view

This is janky but fine except for this path: `Services for a man` > `are you pregnant?`

So questions can be marked [dependent on a facet value](https://github.com/openlexington/finda/blob/gh-pages/config.json#L83) to address this issue. At render time, we skip to the next facet if the [current facet does not meet the dependency](https://github.com/openlexington/finda/blob/gh-pages/src/ui/facet.js#L65).
### A back mechanism needs to skip previous unmet dependencies

So `Services for a man` > skip pregnancy question > `Treatment for adult or child` needs to skip the pregnancy question when the back button is clicked.

It's probably possible to determine unmet dependencies ahead of time so that we [set the `data-next-facet-offset`](https://github.com/openlexington/finda/blob/gh-pages/src/ui/facet.js#L99) value to +2 (or -1, -2, etc for "back").
### Alternatives welcome

That said, there are undoubtedly better ways to pull this off so make it happen! For instance, it'd be great to [keep track of the facet values in the url](#5). Then moving "back" would be a simple `window.history.back()`

**Comment by cheshire137** [comment]
I'm looking at this one.
