### ISSUE TITLE
[non-facet data] add notes

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#133]
when a user reveals more information about the treatment facility, they can see notes about the facility from the spreadsheet database. 

data will likely be limited to a sentence or two. 

restricting the display to a limited number of characters is acceptable if the amount of information is larger than the area available to work with.

**Comment by chaserx** [comment]
similar to issue #106

**Comment by ronnorthrip** [comment]
closed by Feature/106 133 add additional notes to facilities listing #136
