### ISSUE TITLE
OR facet choices rather than AND them

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/gethelplex#19]
Change the [facet type setting](https://github.com/openlexington/finda/blob/gh-pages/config.json#L61) so that multiple selections increase (by OR-ing them) the results rather than narrow them down (AND-ing them).

The CodeforBoston wiki [describes facet config](https://github.com/codeforboston/finda/wiki/Configuration) a bit. [The code](https://github.com/openlexington/finda/blob/gh-pages/src/data/facet.js#L174) that decides facet behavior may be more helpful.

**Comment by eeeschwartz** [comment]
To figure out the number of filtered results, running this in the browser console may be helpful: `$('#list li:visible').length`

**Comment by chaserx** [comment]
~~I also notice the use of `_.intersection` here: https://github.com/openlexington/finda/blob/gh-pages/src/data/facet.js#L48~~ nope. turning .intersection in to .union returns lumps all features together.

**Comment by eeeschwartz** [comment]
@chaserx after looking closer, I think the filters are behaving as ORs already. The issue occurs when a facility does not have a value for a facet.

For example, with `Type of Treatment`:
- With no values selected, there are 116 facilities
- Select `Outpatient`: 68
- Select `Residential`: 102

`$('#list li:not(:visible)')` includes "Addiction Recovery Care and Odyssey Inc" which does not have a value for Outpatient or Residential so it doesn't appear in the OR'd results.

But a sanity check would be great before I run it by Amanda. The [spreadsheet](https://docs.google.com/spreadsheets/d/1ubx07oylGxk5FDIjMnQo4cMNBd3a8QYiPm27rWuyByI/edit#gid=145432932) for reference
