### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/gethelplex#46]
@chaserx sorry for the delay- totally missed this question! We'll let lfucg own it and give openlex access if that works for you.

**Comment by chaserx** [comment]
who's account? lfucg's? openlex? personal?

**Comment by chaserx** [comment]
replace variable name and value as appropriate here: https://github.com/openlexington/finda/blob/gh-pages/src/data/analytics.js#L13

**Comment by chaserx** [comment]
works for me
