### ISSUE TITLE
add legal disclaimer to feedback submission

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#50]

**Comment by eeeschwartz** [comment]
Talked to Amy: let's put a checkbox on the feedback submission form. "I understand that this form is not for treament... I have read the disclaimer." The disclaimer would be an accordion to the full legal text.

I'll get the exact wording from Amy and follow up.

**Comment by eeeschwartz** [comment]
On 'More information' we'll also replace the send bug reports... to gethelplex@lexingtonky.gov with a link to open the feedback widget. 

That way all feedback is routed through widget rather than some being direct email

**Comment by eeeschwartz** [comment]
I'm also pointing the feedback submission at a Google Spreadsheet that will email us upon submission. I couldn't figure out how to nicely notify and display submissions through Google Analytics in #79.
