### ISSUE TITLE
hotjar popup not shown when using the custom domain name

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#63]
check hotjar config

**Comment by chaserx** [comment]
I'm not sure what hotjar is actually doing. I don't think it's config'd.

**Comment by chaserx** [comment]
If we're using this for feedback. Maybe we should opt into another user feedback service.

**Comment by eeeschwartz** [comment]
Good call. I'm not sure Hotjar is the best service for collecting 'Anything wrong' feedback. 

@chaserx do you have any others you've been happy with in the past?

**Comment by chaserx** [comment]
Hmmm. No good ones. I think maybe UserVoice once-upon-a-time and most of them are paid services.

UserSnap looks interesting. https://usersnap.com/ but $19/mo. Maybe they could donate services. Maybe @ondrae knows of some good options 

I think just some form that drops into GitHub Issues with some labels would be ideal.

**Comment by chaserx** [comment]
Ben Balter has some interesting services to get data into a github issue. See: https://github.com/benbalter/comment-card 
and
https://github.com/benbalter/problem_child

**Comment by eeeschwartz** [comment]
Look like good options. 

Found another that submits feedback to Google Analytics called [ga-feedback](https://github.com/luckyshot/ga-feedback). It would be good if stakeholders would prefer that feedback not be immediately made public.

**Comment by eeeschwartz** [comment]
Ben Balter's project require that we host them yeah? Worth weighing that versus the javascript-based ga-feedback.

**Comment by eeeschwartz** [comment]
Although, I'm not sure if the ga-feedback thing would integrate with recaptcha if we need that down the line to keep spammers away.

**Comment by chaserx** [comment]
I'm down to use ga-feedback.

**Comment by eeeschwartz** [comment]
Great. I'll give ga-feedback a try and report back.

**Comment by eeeschwartz** [comment]
Consensus is to move away from hotjar. Closing in favor of #48
