### ISSUE TITLE
Add series of questions on first visit

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/gethelplex#9]
Amy and Amanda got feedback that questions would be helpful up front. The main point was to avoid information overload where you're greeted with a big list of facilities.

With the [new data](#8) I bet we can support their [suggested questions](https://view.officeapps.live.com/op/view.aspx?src=openlexington.github.io%2Ffinda%2Frules-engine-questions.docx) with @chaserx's UI from back in the day:

![wizard mockups](https://raw.githubusercontent.com/openlexington/gethelpky/master/mockups/PNGs/landing.png)

**Comment by chaserx** [comment]
@eeeschwartz I like where the latest is headed.
