### ISSUE TITLE
Update Welcome

### ISSUE THREAD

**Issue by chaserx** [openlexington/gethelplex#97]
On the first screen remove beginning question “Do you or someone you know need access to substance abuse treatment services?”

Add statement “I am interested in information about:   add five buttons that will link you to specific information related to that button.   Assessments (takes you to document), Medical Detox (takes you to document, available below) Residential or Outpatient (this will take you to beginning of locator, where the “yes” button take you now), Medication Assisted Treatment (takes you to document for MAT), Twelve Step Programs (takes you to document for 12 Step Programs).  The Assessment, Medical Detox and Twelve Step information is listed toward the end of the document.  The links for Medication Assisted Treatment are located about ¾ in to the document.

**Comment by c-ro** [comment]
Tried working on this but I'm not sure what document is being referred to - am I missing something?

**Comment by chaserx** [comment]
oh right. my mistake. @c-ro here's the link: https://docs.google.com/document/d/1AIAYmVSuo-QiMPdKNLfFRhvDMx_GYZ6nRUQR8gumOHU/edit?usp=sharing

**Comment by chaserx** [comment]
closed by #112
